apiVersion: 1

datasources:
  - name: Quickwit
    type: quickwit-quickwit-datasource
    uid: quickwit-logs
    access: proxy
    url: http://quickwit:7280/api/v1
    isDefault: false
    jsonData:
      index: "docker-logs"
      timeField: "timestamp"
      logMessageField: "message"
      logLevelField: "level"
    editable: false
